### ISSUE TITLE
Should Asset Helpers Work With Digests?

### ISSUE THREAD

**Issue by metaskills** [metaskills/less-rails#9]
Spawed from ticket #3 which mentioned that given this.

``` css
.myimage() {
  background-image: image-url("less_framework/less.png");
}
#container {
  .myimage();
}
```

Compiles with `rake assets:precompile` to this content `#container{background-image:url(/assets/less_framework/less.png);}`. The question is should there be a digest in that asset url? Here is what is output to the assets directory.
- less_framework/less-ef9b99c1df7d13853cb626bdf3f1f269.png
- less_framework/less.png

Will need to look at sass-rails and see if it does this too. Feedback appreciated.
